FROM mysql:5.6

ENV MYSQL_DATABASE=oh
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_USER=isf
ENV MYSQL_PASSWORD=isf123

#COPY mysql/db/step_00_create_user.sql /docker-entrypoint-initdb.d/
COPY mysql/db/step_01_create_structure.sql /docker-entrypoint-initdb.d/
COPY mysql/db/step_02_dump_menu.sql /docker-entrypoint-initdb.d/
COPY mysql/db/step_03_dump_default_data_it.sql /docker-entrypoint-initdb.d/
#COPY mysql/db/from_step_05.sql /docker-entrypoint-initdb.d/
COPY mysql/db/step_05_update_menu_i18n.sql /docker-entrypoint-initdb.d/
COPY mysql/db/step_06_opd_extended.sql /docker-entrypoint-initdb.d/
COPY mysql/db/step_07_modifiche_matiri.sql /docker-entrypoint-initdb.d/
COPY mysql/db/step_08_int_restore_del_labrestype.sql /docker-entrypoint-initdb.d/
COPY mysql/db/step_09_update_agetype.sql /docker-entrypoint-initdb.d/
COPY mysql/db/step_1* /docker-entrypoint-initdb.d/
COPY mysql/db/step_2* /docker-entrypoint-initdb.d/
COPY mysql/db/step_3* /docker-entrypoint-initdb.d/
COPY mysql/db/step_4* /docker-entrypoint-initdb.d/
COPY mysql/db/step_5* /docker-entrypoint-initdb.d/
COPY mysql/db/data_en/* data_en/
COPY mysql/db/data_es/* data_es/
COPY mysql/db/data_it/* data_it/
#COPY mysql/cnf/my.cnf /etc/mysql/conf.d