.\"     Title: \fBmysqldump\fR
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 01/11/2008
.\"    Manual: MySQL Database System
.\"    Source: MySQL 5.0
.\"
.TH "\fBMYSQLDUMP\fR" "1" "01/11/2008" "MySQL 5.0" "MySQL Database System"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
mysqldump \- a database backup program
.SH "SYNOPSIS"
.HP 45
\fBmysqldump [\fR\fB\fIoptions\fR\fR\fB] [\fR\fB\fIdb_name\fR\fR\fB [\fR\fB\fItbl_name\fR\fR\fB ...]]\fR
.SH "DESCRIPTION"
.PP
The
\fBmysqldump\fR
client is a backup program originally written by Igor Romanenko. It can be used to dump a database or a collection of databases for backup or transfer to another SQL server (not necessarily a MySQL server). The dump typically contains SQL statements to create the table, populate it, or both. However,
\fBmysqldump\fR
can also be used to generate files in CSV, other delimited text, or XML format.
.PP
If you are doing a backup on the server and your tables all are
MyISAM
tables, consider using the
\fBmysqlhotcopy\fR
instead because it can accomplish faster backups and faster restores. See
\fBmysqlhotcopy\fR(1).
.PP
There are three general ways to invoke
\fBmysqldump\fR:
.sp
.RS 3n
.nf
shell> \fBmysqldump [\fR\fB\fIoptions\fR\fR\fB] \fR\fB\fIdb_name\fR\fR\fB [\fR\fB\fItables\fR\fR\fB]\fR
shell> \fBmysqldump [\fR\fB\fIoptions\fR\fR\fB] \-\-databases \fR\fB\fIdb_name1\fR\fR\fB [\fR\fB\fIdb_name2\fR\fR\fB \fR\fB\fIdb_name3\fR\fR\fB...]\fR
shell> \fBmysqldump [\fR\fB\fIoptions\fR\fR\fB] \-\-all\-databases\fR
.fi
.RE
.PP
If you do not name any tables following
\fIdb_name\fR
or if you use the
\fB\-\-databases\fR
or
\fB\-\-all\-databases\fR
option, entire databases are dumped.
.PP
To get a list of the options your version of
\fBmysqldump\fR
supports, execute
\fBmysqldump \-\-help\fR.
.PP
Some
\fBmysqldump\fR
options are shorthand for groups of other options.
\fB\-\-opt\fR
and
\fB\-\-compact\fR
fall into this category. For example, use of
\fB\-\-opt\fR
is the same as specifying
\fB\-\-add\-drop\-table \-\-add\-locks \-\-create\-options \-\-disable\-keys \-\-extended\-insert \-\-lock\-tables \-\-quick \-\-set\-charset\fR. Note that all of the options that
\fB\-\-opt\fR
stands for also are on by default because
\fB\-\-opt\fR
is on by default.
.PP
To reverse the effect of a group option, uses its
\fB\-\-skip\-\fR\fB\fIxxx\fR\fR
form (\fB\-\-skip\-opt\fR
or
\fB\-\-skip\-compact\fR). It is also possible to select only part of the effect of a group option by following it with options that enable or disable specific features. Here are some examples:
.TP 3n
\(bu
To select the effect of
\fB\-\-opt\fR
except for some features, use the
\fB\-\-skip\fR
option for each feature. For example, to disable extended inserts and memory buffering, use
\fB\-\-opt \-\-skip\-extended\-insert \-\-skip\-quick\fR. (As of MySQL 5.0,
\fB\-\-skip\-extended\-insert \-\-skip\-quick\fR
is sufficient because
\fB\-\-opt\fR
is on by default.)
.TP 3n
\(bu
To reverse
\fB\-\-opt\fR
for all features except index disabling and table locking, use
\fB\-\-skip\-opt \-\-disable\-keys \-\-lock\-tables\fR.
.sp
.RE
.PP
When you selectively enable or disable the effect of a group option, order is important because options are processed first to last. For example,
\fB\-\-disable\-keys \-\-lock\-tables \-\-skip\-opt\fR
would not have the intended effect; it is the same as
\fB\-\-skip\-opt\fR
by itself.
.PP
\fBmysqldump\fR
can retrieve and dump table contents row by row, or it can retrieve the entire content from a table and buffer it in memory before dumping it. Buffering in memory can be a problem if you are dumping large tables. To dump tables row by row, use the
\fB\-\-quick\fR
option (or
\fB\-\-opt\fR, which enables
\fB\-\-quick\fR).
\fB\-\-opt\fR
(and hence
\fB\-\-quick\fR) is enabled by default as of MySQL 5.0 to enable memory buffering, use
\fB\-\-skip\-quick\fR.
.PP
If you are using a recent version of
\fBmysqldump\fR
to generate a dump to be reloaded into a very old MySQL server, you should not use the
\fB\-\-opt\fR
or
\fB\-\-extended\-insert\fR
option. Use
\fB\-\-skip\-opt\fR
instead.
.PP
Before MySQL 4.1.2, out\-of\-range numeric values such as
\-inf
and
inf, as well as
NaN
(not\-a\-number) values are dumped by
\fBmysqldump\fR
as
NULL. You can see this using the following sample table:
.sp
.RS 3n
.nf
mysql> \fBCREATE TABLE t (f DOUBLE);\fR
mysql> \fBINSERT INTO t VALUES(1e+111111111111111111111);\fR
mysql> \fBINSERT INTO t VALUES(\-1e111111111111111111111);\fR
mysql> \fBSELECT f FROM t;\fR
+\-\-\-\-\-\-+
| f    |
+\-\-\-\-\-\-+
|  inf |
| \-inf |
+\-\-\-\-\-\-+
.fi
.RE
.PP
For this table,
\fBmysqldump\fR
produces the following data output:
.sp
.RS 3n
.nf
\-\-
\-\- Dumping data for table `t`
\-\-
INSERT INTO t VALUES (NULL);
INSERT INTO t VALUES (NULL);
.fi
.RE
.PP
The significance of this behavior is that if you dump and restore the table, the new table has contents that differ from the original contents. This problem is fixed as of MySQL 4.1.2; you cannot insert
inf
in the table, so this
\fBmysqldump\fR
behavior is only relevant when you deal with old servers.
.PP
\fBmysqldump\fR
supports the following options:
.PP
.B Table\ 4.5.\ \fBmysqldump\fR Option Reference
.sp -1n
.TS
allbox tab(:);
lB lB lB lB.
T{
\fBFormat\fR
T}:T{
\fBConfig File\fR
T}:T{
\fBDescription\fR
T}:T{
\fBIntroduced\fR
T}
.T&
l l l l
l l ^ l
l l l l
l l l l
l l l l
l l ^ l
l l l l
l l l l
l l ^ l
l l l l
l l l l
l l l l
l l l l
l l ^ l
l l l l
l l l l
l l ^ l
l l l l
l l ^ l
l l l l
l l l l
l l l l
l l l l
l l l l
l l l l
l l l l
l l ^ l
l l l l
l l l l
l l ^ l
l l l l
l l l l
l l l l
l l l l
l l l l
l l l l
l l ^ l
l l l l
l l l l
l l l l
l l l l
l l l l
l l l l
l l l l
l l ^ l
l l ^ l
l l l l
l l ^ l
l l l l
l l l l
l l l l
l l l l
l l ^ l
l l l l
l l ^ l
l l l l
l l l l
l l l l
l l ^ l
l l l l
l l ^ l
l l l l
l l l l
l l l l
l l l l
l l l l
l l ^ l
l l l l
l l l l
l l l l
l l l l
l l l l
l l l l
l l l l
l l l l
l l l l
l l l l
l l l l
l l l l
l l l l
l l l l
l l l l
l l l l
l l l l
l l ^ l
l l l l
l l l l
l l l l
l l l l
l l l l
l l ^ l
l l l l
l l ^ l
l l l l
l l ^ l
l l l l
l l ^ l.
T{
\-\-add\-drop\-database
T}:T{
add\-drop\-database
T}:T{
Add a DROP DATABASE statement before each CREATE DATABASE  statement
T}:T{
\ 
T}
T{
\-i
T}:T{
\ 
T}::T{
\ 
T}
T{
\-\-compact
T}:T{
compact
T}:T{
Produce less verbose output
T}:T{
\ 
T}
T{
\-\-compatible=name[,name,...]
T}:T{
compatible
T}:T{
Produce output that is more compatible with other database systems  or with older MySQL servers
T}:T{
\ 
T}
T{
\-\-complete\-insert
T}:T{
complete\-insert
T}:T{
Use complete INSERT statements that include column names
T}:T{
\ 
T}
T{
\-c
T}:T{
\ 
T}::T{
\ 
T}
T{
\-\-create\-options
T}:T{
create\-options
T}:T{
Include all MySQL\-specific table options in the CREATE TABLE  statements
T}:T{
\ 
T}
T{
\-\-databases
T}:T{
databases
T}:T{
Dump several databases
T}:T{
\ 
T}
T{
\-D
T}:T{
\ 
T}::T{
\ 
T}
T{
\-\-delayed\-insert
T}:T{
delayed\-insert
T}:T{
Write INSERT DELAYED statements rather than INSERT statements
T}:T{
\ 
T}
T{
\-\-delete\-master\-logs
T}:T{
delete\-master\-logs
T}:T{
On a master replication server, delete the binary logs after  performing the dump operation
T}:T{
\ 
T}
T{
\-\-add\-drop\-table
T}:T{
add\-drop\-table
T}:T{
Add a DROP TABLE statement before each CREATE TABLE statement
T}:T{
\ 
T}
T{
\-\-disable\-keys
T}:T{
disable\-keys
T}:T{
For each table, surround the INSERT statements with disable and  enable keys statements
T}:T{
\ 
T}
T{
\-K
T}:T{
\ 
T}::T{
\ 
T}
T{
\-\-dump\-date
T}:T{
dump\-date
T}:T{
Include dump date in "Dump completed on" comment if \-\-comments is given
T}:T{
5.0.52
T}
T{
\-\-events
T}:T{
events
T}:T{
Dump events from the dumped databases
T}:T{
\ 
T}
T{
\-E
T}:T{
\ 
T}::T{
\ 
T}
T{
\-\-extended\-insert
T}:T{
extended\-insert
T}:T{
Use multiple\-row INSERT syntax that include several VALUES lists
T}:T{
\ 
T}
T{
\-e
T}:T{
\ 
T}::T{
\ 
T}
T{
\-\-fields\-enclosed\-by=string
T}:T{
fields\-enclosed\-by
T}:T{
This option is used with the \-T option and has the same meaning as  the corresponding clause for LOAD DATA INFILE
T}:T{
\ 
T}
T{
\-\-fields\-escaped\-by
T}:T{
fields\-escaped\-by
T}:T{
This option is used with the \-T option and has the same meaning as  the corresponding clause for LOAD DATA INFILE
T}:T{
\ 
T}
T{
\-\-fields\-optionally\-enclosed\-by=string
T}:T{
fields\-optionally\-enclosed\-by
T}:T{
This option is used with the \-T option and has the same meaning as  the corresponding clause for LOAD DATA INFILE
T}:T{
\ 
T}
T{
\-\-add\-locks
T}:T{
add\-locks
T}:T{
Surround each table dump with LOCK TABLES and UNLOCK TABLES  statements
T}:T{
\ 
T}
T{
\-\-fields\-terminated\-by=string
T}:T{
fields\-terminated\-by
T}:T{
This option is used with the \-T option and has the same meaning  as the corresponding clause for LOAD DATA INFILE
T}:T{
\ 
T}
T{
\-\-lock\-all\-tables
T}:T{
first\-slave
T}:T{
Deprecated. Now renamed to \-\-lock\-all\-tables
T}:T{
\ 
T}
T{
\-\-flush\-logs
T}:T{
flush\-logs
T}:T{
Flush the MySQL server log files before starting the dump
T}:T{
\ 
T}
T{
\-F
T}:T{
\ 
T}::T{
\ 
T}
T{
\-\-flush\-privileges
T}:T{
flush\-privileges
T}:T{
Emit a FLUSH PRIVILEGES statement after dumping the mysql database
T}:T{
\ 
T}
T{
\-\-help
T}:T{
\ 
T}:T{
Display help message and exit
T}:T{
\ 
T}
T{
\-?
T}:T{
\ 
T}::T{
\ 
T}
T{
\-\-hex\-blob
T}:T{
hex\-blob
T}:T{
Dump binary columns using hexadecimal notation (for example, 'abc'  becomes 0x616263)
T}:T{
\ 
T}
T{
\-\-ignore\-table=db_name.tbl_name
T}:T{
ignore\-table
T}:T{
Do not dump the given table
T}:T{
\ 
T}
T{
\-\-insert\-ignore
T}:T{
insert\-ignore
T}:T{
Write INSERT statements with the IGNORE option
T}:T{
\ 
T}
T{
\-\-all\-databases
T}:T{
all\-databases
T}:T{
Dump all tables in all databases
T}:T{
\ 
T}
T{
\-\-lines\-terminated\-by=string
T}:T{
lines\-terminated\-by
T}:T{
This option is used with the \-T option and has the same meaning as  the corresponding clause for LOAD DATA INFILE
T}:T{
\ 
T}
T{
\-\-lock\-all\-tables
T}:T{
lock\-all\-tables
T}:T{
Lock all tables across all databases
T}:T{
\ 
T}
T{
\-x
T}:T{
\ 
T}::T{
\ 
T}
T{
\-\-lock\-tables
T}:T{
lock\-tables
T}:T{
Lock all tables before dumping them
T}:T{
\ 
T}
T{
\-\-log\-error=file_name
T}:T{
log\-error
T}:T{
Append warnings and errors to the named file
T}:T{
5.0.42
T}
T{
\-\-master\-data[=value]
T}:T{
master\-data
T}:T{
Write the binary log filename and position to the output
T}:T{
\ 
T}
T{
\-\-max_allowed_packet=value
T}:T{
max_allowed_packet
T}:T{
The maximum packet length to send to or receive from the server
T}:T{
\ 
T}
T{
\-\-net_buffer_length=value
T}:T{
net_buffer_length
T}:T{
The buffer size for TCP/IP and socket communication
T}:T{
\ 
T}
T{
\-\-no\-autocommit
T}:T{
no\-autocommit
T}:T{
Enclose the INSERT statements for each dumped table within SET  AUTOCOMMIT=0 and COMMIT statements
T}:T{
\ 
T}
T{
\-\-no\-create\-db
T}:T{
no\-create\-db
T}:T{
This option suppresses the CREATE DATABASE statements
T}:T{
\ 
T}
T{
\-A
T}:T{
\ 
T}::T{
\ 
T}
T{
\-n
T}:T{
\ 
T}::T{
\ 
T}
T{
\-\-no\-create\-info
T}:T{
no\-create\-info
T}:T{
Do not write CREATE TABLE statements that re\-create each dumped  table
T}:T{
\ 
T}
T{
\-t
T}:T{
\ 
T}::T{
\ 
T}
T{
\-\-no\-set\-names
T}:T{
no\-set\-names
T}:T{
Turn off complete\-insert
T}:T{
\ 
T}
T{
\-\-opt
T}:T{
opt
T}:T{
This option is shorthand; it is the same as specifying  \-\-add\-drop\-table \-\-add\-locks \-\-create\-options \-\-disable\-keys  \-\-extended\-insert \-\-lock\-tables \-\-quick \-\-set\-charset.
T}:T{
\ 
T}
T{
\-\-order\-by\-primary
T}:T{
order\-by\-primary
T}:T{
Sorts each table's rows by its primary key, or by its first unique  index
T}:T{
\ 
T}
T{
\-\-quick
T}:T{
quick
T}:T{
Retrieve rows for a table from the server a row at a time
T}:T{
\ 
T}
T{
\-q
T}:T{
\ 
T}::T{
\ 
T}
T{
\-\-quote\-names
T}:T{
quote\-names
T}:T{
Quote database, table, and column names within backtick characters
T}:T{
\ 
T}
T{
\-Q
T}:T{
\ 
T}::T{
\ 
T}
T{
\-\-all\-tablespaces
T}:T{
all\-tablespaces
T}:T{
Adds to a table dump all SQL statements needed to create any  tablespaces used by an NDB Cluster table
T}:T{
\ 
T}
T{
\-\-replace
T}:T{
replace
T}:T{
Write REPLACE statements rather than INSERT statements
T}:T{
\ 
T}
T{
\-\-result\-file=file
T}:T{
result\-file
T}:T{
Direct output to a given file
T}:T{
\ 
T}
T{
\-r file
T}:T{
\ 
T}::T{
\ 
T}
T{
\-\-routines
T}:T{
routines
T}:T{
Dump stored routines (functions and procedures) from the dumped  databases
T}:T{
\ 
T}
T{
\-R
T}:T{
\ 
T}::T{
\ 
T}
T{
\-\-set\-charset
T}:T{
set\-charset
T}:T{
Add SET NAMES default_character_set to the output
T}:T{
\ 
T}
T{
\-\-single\-transaction
T}:T{
single\-transaction
T}:T{
This option issues a BEGIN SQL statement before dumping data from  the server
T}:T{
\ 
T}
T{
\-\-skip\-add\-drop\-table
T}:T{
skip\-add\-drop\-table
T}:T{
Do not add
T}:T{
\ 
T}
T{
\-\-skip\-add\-locks
T}:T{
skip\-add\-locks
T}:T{
Do not add locks
T}:T{
\ 
T}
T{
\-\-skip\-comments
T}:T{
skip\-comments
T}:T{
Do not add comments to the dump file
T}:T{
\ 
T}
T{
\-Y
T}:T{
\ 
T}::T{
\ 
T}
T{
\-\-skip\-compact
T}:T{
skip\-compact
T}:T{
Turn off compact
T}:T{
\ 
T}
T{
\-\-skip\-disable\-keys
T}:T{
skip\-disable\-keys
T}:T{
Do not disable keys
T}:T{
\ 
T}
T{
\-\-skip\-extended\-insert
T}:T{
skip\-extended\-insert
T}:T{
Turn off extended\-insert
T}:T{
\ 
T}
T{
\-\-skip\-opt
T}:T{
skip\-opt
T}:T{
Turn off the options set by opt
T}:T{
\ 
T}
T{
\-\-skip\-quick
T}:T{
skip\-quick
T}:T{
Do not retrieve rows for a table from the server a row at a time
T}:T{
\ 
T}
T{
\-\-skip\-quote\-names
T}:T{
skip\-quote\-names
T}:T{
Turn off quote names
T}:T{
\ 
T}
T{
\-skip\-charset
T}:T{
skip\-set\-charset
T}:T{
Suppress the SET NAMES statement
T}:T{
\ 
T}
T{
\-\-skip\-triggers
T}:T{
skip\-triggers
T}:T{
Turn off triggers
T}:T{
5.0.11
T}
T{
\-\-skip\-tz\-utc
T}:T{
skip\-tz\-utc
T}:T{
Turn off tz\-utc
T}:T{
\ 
T}
T{
\-\-ssl\-ca=file_name
T}:T{
ssl\-ca
T}:T{
The path to a file that contains a list of trusted SSL CAs
T}:T{
\ 
T}
T{
\-\-allow\-keywords
T}:T{
allow\-keywords
T}:T{
Allow creation of column names that are keywords
T}:T{
\ 
T}
T{
\-\-ssl\-capath=directory_name
T}:T{
ssl\-capath
T}:T{
The path to a directory that contains trusted SSL CA certificates  in PEM format
T}:T{
\ 
T}
T{
\-\-ssl\-cert=file_name
T}:T{
ssl\-cert
T}:T{
The name of the SSL certificate file to use for establishing a  secure connection
T}:T{
\ 
T}
T{
\-\-ssl\-cipher=cipher_list
T}:T{
ssl\-cipher
T}:T{
A list of allowable ciphers to use for SSL encryption
T}:T{
\ 
T}
T{
\-\-ssl\-key=file_name
T}:T{
ssl\-key
T}:T{
The name of the SSL key file to use for establishing a secure  connection
T}:T{
\ 
T}
T{
\-\-ssl\-verify\-server\-cert
T}:T{
ssl\-verify\-server\-cert
T}:T{
The server's Common Name value in its certificate is verified  against the hostname used when connecting to the server
T}:T{
\ 
T}
T{
\-\-tab=path
T}:T{
tab
T}:T{
Produce tab\-separated data files
T}:T{
\ 
T}
T{
\-T path
T}:T{
\ 
T}::T{
\ 
T}
T{
\-\-tables
T}:T{
tables
T}:T{
Override the \-\-databases or \-B option
T}:T{
\ 
T}
T{
\-\-triggers
T}:T{
triggers
T}:T{
Dump triggers for each dumped table
T}:T{
\ 
T}
T{
\-\-tz\-utc
T}:T{
tz\-utc
T}:T{
Add SET TIME_ZONE='+00:00' to the dump file
T}:T{
\ 
T}
T{
\-\-comments
T}:T{
comments
T}:T{
Add comments to the dump file
T}:T{
\ 
T}
T{
\-\-verbose
T}:T{
\ 
T}:T{
Verbose mode
T}:T{
\ 
T}
T{
\-v
T}:T{
\ 
T}::T{
\ 
T}
T{
\-\-version
T}:T{
\ 
T}:T{
Display version information and exit
T}:T{
\ 
T}
T{
\-V
T}:T{
\ 
T}::T{
\ 
T}
T{
\-\-where='where_condition'
T}:T{
where
T}:T{
Dump only rows selected by the given WHERE condition
T}:T{
\ 
T}
T{
\-w 'where_condition'
T}:T{
\ 
T}::T{
\ 
T}
T{
\-\-xml
T}:T{
xml
T}:T{
Produce XML output
T}:T{
\ 
T}
T{
\-X
T}:T{
\ 
T}::T{
\ 
T}
.TE
.sp
.TP 3n
\(bu
\fB\-\-help\fR,
\fB\-?\fR
.sp
Display a help message and exit.
.TP 3n
\(bu
\fB\-\-add\-drop\-database\fR
.sp
Add a
DROP DATABASE
statement before each
CREATE DATABASE
statement.
.TP 3n
\(bu
\fB\-\-add\-drop\-table\fR
.sp
Add a
DROP TABLE
statement before each
CREATE TABLE
statement.
.TP 3n
\(bu
\fB\-\-add\-locks\fR
.sp
Surround each table dump with
LOCK TABLES
and
UNLOCK TABLES
statements. This results in faster inserts when the dump file is reloaded. See
Section\ 2.17, \(lqSpeed of INSERT Statements\(rq.
.TP 3n
\(bu
\fB\-\-all\-databases\fR,
\fB\-A\fR
.sp
Dump all tables in all databases. This is the same as using the
\fB\-\-databases\fR
option and naming all the databases on the command line.
.TP 3n
\(bu
\fB\-\-allow\-keywords\fR
.sp
Allow creation of column names that are keywords. This works by prefixing each column name with the table name.
.TP 3n
\(bu
\fB\-\-character\-sets\-dir=\fR\fB\fIpath\fR\fR
.sp
The directory where character sets are installed. See
Section\ 2, \(lqThe Character Set Used for Data and Sorting\(rq.
.TP 3n
\(bu
\fB\-\-comments\fR,
\fB\-i\fR
.sp
Write additional information in the dump file such as program version, server version, and host. This option is enabled by default. To suppress this additional information, use
\fB\-\-skip\-comments\fR.
.TP 3n
\(bu
\fB\-\-compact\fR
.sp
Produce less verbose output. This option enables the
\fB\-\-skip\-add\-drop\-table\fR,
\fB\-\-skip\-add\-locks\fR,
\fB\-\-skip\-comments\fR,
\fB\-\-skip\-disable\-keys\fR, and
\fB\-\-skip\-set\-charset\fR
options.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBNote\fR
Prior to release 5.0.48, this option did not create valid SQL if the database dump contained views. The recreation of views requires the creation and removal of temporary tables and this option suppressed the removal of those temporary tables. As a workaround, use
\fB\-\-compress\fR
with the
\fB\-\-add\-drop\-table\fR
option and then manually adjust the dump file.
.TP 3n
\(bu
\fB\-\-compatible=\fR\fB\fIname\fR\fR
.sp
Produce output that is more compatible with other database systems or with older MySQL servers. The value of
name
can be
ansi,
mysql323,
mysql40,
postgresql,
oracle,
mssql,
db2,
maxdb,
no_key_options,
no_table_options, or
no_field_options. To use several values, separate them by commas. These values have the same meaning as the corresponding options for setting the server SQL mode. See
Section\ 1.6, \(lqSQL Modes\(rq.
.sp
This option does not guarantee compatibility with other servers. It only enables those SQL mode values that are currently available for making dump output more compatible. For example,
\fB\-\-compatible=oracle\fR
does not map data types to Oracle types or use Oracle comment syntax.
.sp
\fIThis option requires a server version of 4.1.0 or higher\fR. With older servers, it does nothing.
.TP 3n
\(bu
\fB\-\-complete\-insert\fR,
\fB\-c\fR
.sp
Use complete
INSERT
statements that include column names.
.TP 3n
\(bu
\fB\-\-compress\fR,
\fB\-C\fR
.sp
Compress all information sent between the client and the server if both support compression.
.TP 3n
\(bu
\fB\-\-create\-options\fR
.sp
Include all MySQL\-specific table options in the
CREATE TABLE
statements.
.TP 3n
\(bu
\fB\-\-databases\fR,
\fB\-B\fR
.sp
Dump several databases. Normally,
\fBmysqldump\fR
treats the first name argument on the command line as a database name and following names as table names. With this option, it treats all name arguments as database names.
CREATE DATABASE
and
USE
statements are included in the output before each new database.
.TP 3n
\(bu
\fB\-\-debug[=\fR\fB\fIdebug_options\fR\fR\fB]\fR,
\fB\-# [\fR\fB\fIdebug_options\fR\fR\fB]\fR
.sp
Write a debugging log. The
\fIdebug_options\fR
string is often
\'d:t:o,\fIfile_name\fR'. The default value is
\'d:t:o,/tmp/mysqldump.trace'.
.TP 3n
\(bu
\fB\-\-default\-character\-set=\fR\fB\fIcharset_name\fR\fR
.sp
Use
\fIcharset_name\fR
as the default character set. See
Section\ 2, \(lqThe Character Set Used for Data and Sorting\(rq. If no character set is specified,
\fBmysqldump\fR
uses
utf8, and earlier versions use
latin1.
.TP 3n
\(bu
\fB\-\-delayed\-insert\fR
.sp
Write
INSERT DELAYED
statements rather than
INSERT
statements.
.TP 3n
\(bu
\fB\-\-delete\-master\-logs\fR
.sp
On a master replication server, delete the binary logs after performing the dump operation. This option automatically enables
\fB\-\-master\-data\fR.
.TP 3n
\(bu
\fB\-\-disable\-keys\fR,
\fB\-K\fR
.sp
For each table, surround the
INSERT
statements with
/*!40000 ALTER TABLE \fItbl_name\fR DISABLE KEYS */;
and
/*!40000 ALTER TABLE \fItbl_name\fR ENABLE KEYS */;
statements. This makes loading the dump file faster because the indexes are created after all rows are inserted. This option is effective only for non\-unique indexes of
MyISAM
tables.
.TP 3n
\(bu
\fB\-\-dump\-date\fR
.sp
\fBmysqldump\fR
produces a
\-\- Dump completed on \fIDATE\fR
comment at the end of the dump if the
\fB\-\-comments\fR
option is given. However, the date causes dump files for identical data take at different times to appear to be different.
\fB\-\-dump\-date\fR
and
\fB\-\-skip\-dump\-date\fR
control whether the date is added to the comment. The default is
\fB\-\-dump\-date\fR
(include the date in the comment).
\fB\-\-skip\-dump\-date\fR
suppresses date printing. This option was added in MySQL 5.0.52.
.TP 3n
\(bu
\fB\-\-extended\-insert\fR,
\fB\-e\fR
.sp
Use multiple\-row
INSERT
syntax that include several
VALUES
lists. This results in a smaller dump file and speeds up inserts when the file is reloaded.
.TP 3n
\(bu
\fB\-\-fields\-terminated\-by=...\fR,
\fB\-\-fields\-enclosed\-by=...\fR,
\fB\-\-fields\-optionally\-enclosed\-by=...\fR,
\fB\-\-fields\-escaped\-by=...\fR
.sp
These options are used with the
\fB\-T\fR
option and have the same meaning as the corresponding clauses for
LOAD DATA INFILE. See
Section\ 2.5, \(lqLOAD DATA INFILE Syntax\(rq.
.TP 3n
\(bu
\fB\-\-first\-slave\fR,
\fB\-x\fR
.sp
Deprecated. Now renamed to
\fB\-\-lock\-all\-tables\fR.
.TP 3n
\(bu
\fB\-\-flush\-logs\fR,
\fB\-F\fR
.sp
Flush the MySQL server log files before starting the dump. This option requires the
RELOAD
privilege. Note that if you use this option in combination with the
\fB\-\-all\-databases\fR
(or
\fB\-A\fR) option, the logs are flushed
\fIfor each database dumped\fR. The exception is when using
\fB\-\-lock\-all\-tables\fR
or
\fB\-\-master\-data\fR: In this case, the logs are flushed only once, corresponding to the moment that all tables are locked. If you want your dump and the log flush to happen at exactly the same moment, you should use
\fB\-\-flush\-logs\fR
together with either
\fB\-\-lock\-all\-tables\fR
or
\fB\-\-master\-data\fR.
.TP 3n
\(bu
\fB\-\-flush\-privileges\fR
.sp
Emit a
FLUSH PRIVILEGES
statement after dumping the
mysql
database. This option should be used any time the dump contains the
mysql
database and any other database that depends on the data in the
mysql
database for proper restoration. This option was added in MySQL 5.0.26.
.TP 3n
\(bu
\fB\-\-force\fR,
\fB\-f\fR
.sp
Continue even if an SQL error occurs during a table dump.
.sp
One use for this option is to cause
\fBmysqldump\fR
to continue executing even when it encounters a view that has become invalid because the defintion refers to a table that has been dropped. Without
\fB\-\-force\fR,
\fBmysqldump\fR
exits with an error message. With
\fB\-\-force\fR,
\fBmysqldump\fR
prints the error message, but it also writes a SQL comment containing the view definition to the dump output and continues executing.
.TP 3n
\(bu
\fB\-\-host=\fR\fB\fIhost_name\fR\fR,
\fB\-h \fR\fB\fIhost_name\fR\fR
.sp
Dump data from the MySQL server on the given host. The default host is
localhost.
.TP 3n
\(bu
\fB\-\-hex\-blob\fR
.sp
Dump binary columns using hexadecimal notation (for example,
\'abc'
becomes
0x616263). The affected data types are
BINARY,
VARBINARY, and
BLOB. As of MySQL 5.0.13,
BIT
columns are affected as well.
.TP 3n
\(bu
\fB\-\-ignore\-table=\fR\fB\fIdb_name.tbl_name\fR\fR
.sp
Do not dump the given table, which must be specified using both the database and table names. To ignore multiple tables, use this option multiple times.
.TP 3n
\(bu
\fB\-\-insert\-ignore\fR
.sp
Write
INSERT
statements with the
IGNORE
option.
.TP 3n
\(bu
\fB\-\-lines\-terminated\-by=...\fR
.sp
This option is used with the
\fB\-T\fR
option and has the same meaning as the corresponding clause for
LOAD DATA INFILE. See
Section\ 2.5, \(lqLOAD DATA INFILE Syntax\(rq.
.TP 3n
\(bu
\fB\-\-lock\-all\-tables\fR,
\fB\-x\fR
.sp
Lock all tables across all databases. This is achieved by acquiring a global read lock for the duration of the whole dump. This option automatically turns off
\fB\-\-single\-transaction\fR
and
\fB\-\-lock\-tables\fR.
.TP 3n
\(bu
\fB\-\-lock\-tables\fR,
\fB\-l\fR
.sp
Lock all tables before dumping them. The tables are locked with
READ LOCAL
to allow concurrent inserts in the case of
MyISAM
tables. For transactional tables such as
InnoDB
and
BDB,
\fB\-\-single\-transaction\fR
is a much better option, because it does not need to lock the tables at all.
.sp
Please note that when dumping multiple databases,
\fB\-\-lock\-tables\fR
locks tables for each database separately. Therefore, this option does not guarantee that the tables in the dump file are logically consistent between databases. Tables in different databases may be dumped in completely different states.
.TP 3n
\(bu
\fB\-\-log\-error=\fR\fB\fIfile_name\fR\fR
.sp
Append warnings and errors to the named file. This option was added in MySQL 5.0.42.
.TP 3n
\(bu
\fB\-\-master\-data[=\fR\fB\fIvalue\fR\fR\fB]\fR
.sp
Write the binary log filename and position to the output. This option requires the
RELOAD
privilege and the binary log must be enabled. If the option value is equal to 1, the position and filename are written to the dump output in the form of a
CHANGE MASTER
statement. If the dump is from a master server and you use it to set up a slave server, the
CHANGE MASTER
statement causes the slave to start from the correct position in the master's binary logs. If the option value is equal to 2, the
CHANGE MASTER
statement is written as an SQL comment. If the value is not specified, then the default value is 1.
.sp
The
\fB\-\-master\-data\fR
option automatically turns off
\fB\-\-lock\-tables\fR. It also turns on
\fB\-\-lock\-all\-tables\fR, unless
\fB\-\-single\-transaction\fR
also is specified (in which case, a global read lock is acquired only for a short time at the beginning of the dump. See also the description for
\fB\-\-single\-transaction\fR. In all cases, any action on logs happens at the exact moment of the dump.
.TP 3n
\(bu
\fB\-\-no\-autocommit\fR
.sp
Enclose the
INSERT
statements for each dumped table within
SET AUTOCOMMIT=0
and
COMMIT
statements.
.TP 3n
\(bu
\fB\-\-no\-create\-db\fR,
\fB\-n\fR
.sp
This option suppresses the
CREATE DATABASE
statements that are otherwise included in the output if the
\fB\-\-databases\fR
or
\fB\-\-all\-databases\fR
option is given.
.TP 3n
\(bu
\fB\-\-no\-create\-info\fR,
\fB\-t\fR
.sp
Do not write
CREATE TABLE
statements that re\-create each dumped table.
.TP 3n
\(bu
\fB\-\-no\-data\fR,
\fB\-d\fR
.sp
Do not write any table row information (that is, do not dump table contents). This is very useful if you want to dump only the
CREATE TABLE
statement for the table.
.TP 3n
\(bu
\fB\-\-opt\fR
.sp
This option is shorthand; it is the same as specifying
\fB\-\-add\-drop\-table \-\-add\-locks \-\-create\-options \-\-disable\-keys \-\-extended\-insert \-\-lock\-tables \-\-quick \-\-set\-charset\fR. It should give you a fast dump operation and produce a dump file that can be reloaded into a MySQL server quickly.
.sp
\fIThe \fR\fI\fB\-\-opt\fR\fR\fI option is enabled by default. Use \fR\fI\fB\-\-skip\-opt\fR\fR\fI to disable it.\fR
See the discussion at the beginning of this section for information about selectively enabling or disabling certain of the options affected by
\fB\-\-opt\fR.
.TP 3n
\(bu
\fB\-\-order\-by\-primary\fR
.sp
Sorts each table's rows by its primary key, or by its first unique index, if such an index exists. This is useful when dumping a
MyISAM
table to be loaded into an
InnoDB
table, but will make the dump itself take considerably longer.
.TP 3n
\(bu
\fB\-\-password[=\fR\fB\fIpassword\fR\fR\fB]\fR,
\fB\-p[\fR\fB\fIpassword\fR\fR\fB]\fR
.sp
The password to use when connecting to the server. If you use the short option form (\fB\-p\fR), you
\fIcannot\fR
have a space between the option and the password. If you omit the
\fIpassword\fR
value following the
\fB\-\-password\fR
or
\fB\-p\fR
option on the command line, you are prompted for one.
.sp
Specifying a password on the command line should be considered insecure. See
Section\ 5.6, \(lqKeeping Your Password Secure\(rq.
.TP 3n
\(bu
\fB\-\-port=\fR\fB\fIport_num\fR\fR,
\fB\-P \fR\fB\fIport_num\fR\fR
.sp
The TCP/IP port number to use for the connection.
.TP 3n
\(bu
\fB\-\-protocol={TCP|SOCKET|PIPE|MEMORY}\fR
.sp
The connection protocol to use.
.TP 3n
\(bu
\fB\-\-quick\fR,
\fB\-q\fR
.sp
This option is useful for dumping large tables. It forces
\fBmysqldump\fR
to retrieve rows for a table from the server a row at a time rather than retrieving the entire row set and buffering it in memory before writing it out.
.TP 3n
\(bu
\fB\-\-quote\-names\fR,
\fB\-Q\fR
.sp
Quote database, table, and column names within
\(lq`\(rq
characters. If the
ANSI_QUOTES
SQL mode is enabled, names are quoted within
\(lq"\(rq
characters. This option is enabled by default. It can be disabled with
\fB\-\-skip\-quote\-names\fR, but this option should be given after any option such as
\fB\-\-compatible\fR
that may enable
\fB\-\-quote\-names\fR.
.TP 3n
\(bu
\fB\-\-result\-file=\fR\fB\fIfile\fR\fR,
\fB\-r \fR\fB\fIfile\fR\fR
.sp
Direct output to a given file. This option should be used on Windows to prevent newline
\(lq\\n\(rq
characters from being converted to
\(lq\\r\\n\(rq
carriage return/newline sequences. The result file is created and its contents overwritten, even if an error occurs while generating the dump. The previous contents are lost.
.TP 3n
\(bu
\fB\-\-routines\fR,
\fB\-R\fR
.sp
Dump stored routines (functions and procedures) from the dumped databases. Use of this option requires the
SELECT
privilege for the
mysql.proc
table. The output generated by using
\fB\-\-routines\fR
contains
CREATE PROCEDURE
and
CREATE FUNCTION
statements to re\-create the routines. However, these statements do not include attributes such as the routine creation and modification timestamps. This means that when the routines are reloaded, they will be created with the timestamps equal to the reload time.
.sp
If you require routines to be re\-created with their original timestamp attributes, do not use
\fB\-\-routines\fR. Instead, dump and reload the contents of the
mysql.proc
table directly, using a MySQL account that has appropriate privileges for the
mysql
database.
.sp
This option was added in MySQL 5.0.13. Before that, stored routines are not dumped. Routine
DEFINER
values are not dumped until MySQL 5.0.20. This means that before 5.0.20, when routines are reloaded, they will be created with the definer set to the reloading user. If you require routines to be re\-created with their original definer, dump and load the contents of the
mysql.proc
table directly as described earlier.
.TP 3n
\(bu
\fB\-\-set\-charset\fR
.sp
Add
SET NAMES \fIdefault_character_set\fR
to the output. This option is enabled by default. To suppress the
SET NAMES
statement, use
\fB\-\-skip\-set\-charset\fR.
.TP 3n
\(bu
\fB\-\-single\-transaction\fR
.sp
This option issues a
BEGIN
SQL statement before dumping data from the server. It is useful only with transactional tables such as
InnoDB
and
BDB, because then it dumps the consistent state of the database at the time when
BEGIN
was issued without blocking any applications.
.sp
When using this option, you should keep in mind that only
InnoDB
tables are dumped in a consistent state. For example, any
MyISAM
or
MEMORY
tables dumped while using this option may still change state.
.sp
The
\fB\-\-single\-transaction\fR
option and the
\fB\-\-lock\-tables\fR
option are mutually exclusive, because
LOCK TABLES
causes any pending transactions to be committed implicitly.
.sp
While a
\fB\-\-single\-transaction\fR
dump is in process, to ensure a valid dump file (correct table contents and binary log position), no other connection should use the following statements:
ALTER TABLE,
DROP TABLE,
RENAME TABLE,
TRUNCATE TABLE. A consistent read is not isolated from those statements, so use of them on a table to be dumped can cause the
SELECT
performed by
\fBmysqldump\fR
to retrieve the table contents to obtain incorrect contents or fail.
.sp
This option is not supported for MySQL Cluster tables; the results cannot be guaranteed to be consistent due to the fact that the
NDBCluster
storage engine supports only the
READ_COMMITTED
transaction isolation level. You should always use
NDB
backup and restore instead.
.sp
To dump large tables, you should combine this option with
\fB\-\-quick\fR.
.TP 3n
\(bu
\fB\-\-skip\-comments\fR
.sp
See the description for the
\fB\-\-comments\fR
option.
.TP 3n
\(bu
\fB\-\-skip\-opt\fR
.sp
See the description for the
\fB\-\-opt\fR
option.
.TP 3n
\(bu
\fB\-\-socket=\fR\fB\fIpath\fR\fR,
\fB\-S \fR\fB\fIpath\fR\fR
.sp
For connections to
localhost, the Unix socket file to use, or, on Windows, the name of the named pipe to use.
.TP 3n
\(bu
\fB\-\-ssl*\fR
.sp
Options that begin with
\fB\-\-ssl\fR
specify whether to connect to the server via SSL and indicate where to find SSL keys and certificates. See
Section\ 5.7.3, \(lqSSL Command Options\(rq.
.TP 3n
\(bu
\fB\-\-tab=\fR\fB\fIpath\fR\fR,
\fB\-T \fR\fB\fIpath\fR\fR
.sp
Produce tab\-separated data files. For each dumped table,
\fBmysqldump\fR
creates a
\fI\fItbl_name\fR\fR\fI.sql\fR
file that contains the
CREATE TABLE
statement that creates the table, and a
\fI\fItbl_name\fR\fR\fI.txt\fR
file that contains its data. The option value is the directory in which to write the files.
.sp
By default, the
\fI.txt\fR
data files are formatted using tab characters between column values and a newline at the end of each line. The format can be specified explicitly using the
\fB\-\-fields\-\fR\fB\fIxxx\fR\fR
and
\fB\-\-lines\-terminated\-by\fR
options.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
\fBNote\fR
This option should be used only when
\fBmysqldump\fR
is run on the same machine as the
\fBmysqld\fR
server. You must have the
FILE
privilege, and the server must have permission to write files in the directory that you specify.
.TP 3n
\(bu
\fB\-\-tables\fR
.sp
Override the
\fB\-\-databases\fR
or
\fB\-B\fR
option.
\fBmysqldump\fR
regards all name arguments following the option as table names.
.TP 3n
\(bu
\fB\-\-triggers\fR
.sp
Dump triggers for each dumped table. This option is enabled by default; disable it with
\fB\-\-skip\-triggers\fR. This option was added in MySQL 5.0.11. Before that, triggers are not dumped.
.TP 3n
\(bu
\fB\-\-tz\-utc\fR
.sp
Add
SET TIME_ZONE='+00:00'
to the dump file so that
TIMESTAMP
columns can be dumped and reloaded between servers in different time zones. Without this option,
TIMESTAMP
columns are dumped and reloaded in the time zones local to the source and destination servers, which can cause the values to change.
\fB\-\-tz\-utc\fR
also protects against changes due to daylight saving time.
\fB\-\-tz\-utc\fR
is enabled by default. To disable it, use
\fB\-\-skip\-tz\-utc\fR. This option was added in MySQL 5.0.15.
.TP 3n
\(bu
\fB\-\-user=\fR\fB\fIuser_name\fR\fR,
\fB\-u \fR\fB\fIuser_name\fR\fR
.sp
The MySQL username to use when connecting to the server.
.TP 3n
\(bu
\fB\-\-verbose\fR,
\fB\-v\fR
.sp
Verbose mode. Print more information about what the program does.
.TP 3n
\(bu
\fB\-\-version\fR,
\fB\-V\fR
.sp
Display version information and exit.
.TP 3n
\(bu
\fB\-\-where='\fR\fB\fIwhere_condition\fR\fR\fB'\fR,
\fB\-w '\fR\fB\fIwhere_condition\fR\fR\fB'\fR
.sp
Dump only rows selected by the given
WHERE
condition. Quotes around the condition are mandatory if it contains spaces or other characters that are special to your command interpreter.
.sp
Examples:
.sp
.RS 3n
.nf
\-\-where="user='jimf'"
\-w"userid>1"
\-w"userid<1"
.fi
.RE
.TP 3n
\(bu
\fB\-\-xml\fR,
\fB\-X\fR
.sp
Write dump output as well\-formed XML.
.sp
\fBNULL\fR\fB, \fR\fB'NULL'\fR\fB, and Empty Values\fR: For some column named
\fIcolumn_name\fR, the
NULL
value, an empty string, and the string value
\'NULL'
are distinguished from one another in the output generated by this option as follows:
.TS
allbox tab(:);
l l
l l
l l
l l.
T{
\fBValue\fR:
T}:T{
\fBXML Representation\fR:
T}
T{
NULL (\fIunknown value\fR)
T}:T{
<field name="\fIcolumn_name\fR"
                    xsi:nil="true" />
T}
T{
\'' (\fIempty string\fR)
T}:T{
<field
                    name="\fIcolumn_name\fR"></field>
T}
T{
\'NULL' (\fIstring value\fR)
T}:T{
<field
                    name="\fIcolumn_name\fR">NULL</field>
T}
.TE
.sp
Beginning with MySQL 5.0.26, the output from the
\fBmysql\fR
client when run using the
\fB\-\-xml\fR
option also follows these rules. (See
the section called \(lq\fBMYSQL\fR OPTIONS\(rq.)
.sp
Beginning with MySQL 5.0.40, XML output from
\fBmysqldump\fR
includes the XML namespace, as shown here:
.sp
.RS 3n
.nf
shell> \fBmysqldump \-\-xml \-u root world City\fR
<?xml version="1.0"?>
<mysqldump xmlns:xsi="http://www.w3.org/2001/XMLSchema\-instance">
<database name="world">
<table_structure name="City">
<field Field="ID" Type="int(11)" Null="NO" Key="PRI" Extra="auto_increment" />
<field Field="Name" Type="char(35)" Null="NO" Key="" Default="" Extra="" />
<field Field="CountryCode" Type="char(3)" Null="NO" Key="" Default="" Extra="" />
<field Field="District" Type="char(20)" Null="NO" Key="" Default="" Extra="" />
<field Field="Population" Type="int(11)" Null="NO" Key="" Default="0" Extra="" />
<key Table="City" Non_unique="0" Key_name="PRIMARY" Seq_in_index="1" Column_name="ID" Collation="A" Cardinality="4079"
Null="" Index_type="BTREE" Comment="" />
<options Name="City" Engine="MyISAM" Version="10" Row_format="Fixed" Rows="4079" Avg_row_length="67" Data_length="27329
3" Max_data_length="18858823439613951" Index_length="43008" Data_free="0" Auto_increment="4080" Create_time="2007\-03\-31 01:47:01" Updat
e_time="2007\-03\-31 01:47:02" Collation="latin1_swedish_ci" Create_options="" Comment="" />
</table_structure>
<table_data name="City">
<row>
<field name="ID">1</field>
<field name="Name">Kabul</field>
<field name="CountryCode">AFG</field>
<field name="District">Kabol</field>
<field name="Population">1780000</field>
</row>
\fI...\fR
<row>
<field name="ID">4079</field>
<field name="Name">Rafah</field>
<field name="CountryCode">PSE</field>
<field name="District">Rafah</field>
<field name="Population">92020</field>
</row>
</table_data>
</database>
</mysqldump>
.fi
.RE
.sp
.sp
.RE
.PP
You can also set the following variables by using
\fB\-\-\fR\fB\fIvar_name\fR\fR\fB=\fR\fB\fIvalue\fR\fR
syntax:
.TP 3n
\(bu
max_allowed_packet
.sp
The maximum size of the buffer for client/server communication. The maximum is 1GB.
.TP 3n
\(bu
net_buffer_length
.sp
The initial size of the buffer for client/server communication. When creating multiple\-row\-insert statements (as with option
\fB\-\-extended\-insert\fR
or
\fB\-\-opt\fR),
\fBmysqldump\fR
creates rows up to
net_buffer_length
length. If you increase this variable, you should also ensure that the
net_buffer_length
variable in the MySQL server is at least this large.
.sp
.RE
.PP
It is also possible to set variables by using
\fB\-\-set\-variable=\fR\fB\fIvar_name\fR\fR\fB=\fR\fB\fIvalue\fR\fR
or
\fB\-O \fR\fB\fIvar_name\fR\fR\fB=\fR\fB\fIvalue\fR\fR
syntax.
\fIThis syntax is deprecated\fR.
.PP
The most common use of
\fBmysqldump\fR
is probably for making a backup of an entire database:
.sp
.RS 3n
.nf
shell> \fBmysqldump \fR\fB\fIdb_name\fR\fR\fB > \fR\fB\fIbackup\-file.sql\fR\fR
.fi
.RE
.PP
You can read the dump file back into the server like this:
.sp
.RS 3n
.nf
shell> \fBmysql \fR\fB\fIdb_name\fR\fR\fB < \fR\fB\fIbackup\-file.sql\fR\fR
.fi
.RE
.PP
Or like this:
.sp
.RS 3n
.nf
shell> \fBmysql \-e "source \fR\fB\fI/path\-to\-backup/backup\-file.sql\fR\fR\fB" \fR\fB\fIdb_name\fR\fR
.fi
.RE
.PP
\fBmysqldump\fR
is also very useful for populating databases by copying data from one MySQL server to another:
.sp
.RS 3n
.nf
shell> \fBmysqldump \-\-opt \fR\fB\fIdb_name\fR\fR\fB | mysql \-\-host=\fR\fB\fIremote_host\fR\fR\fB \-C \fR\fB\fIdb_name\fR\fR
.fi
.RE
.PP
It is possible to dump several databases with one command:
.sp
.RS 3n
.nf
shell> \fBmysqldump \-\-databases \fR\fB\fIdb_name1\fR\fR\fB [\fR\fB\fIdb_name2\fR\fR\fB ...] > my_databases.sql\fR
.fi
.RE
.PP
To dump all databases, use the
\fB\-\-all\-databases\fR
option:
.sp
.RS 3n
.nf
shell> \fBmysqldump \-\-all\-databases > all_databases.sql\fR
.fi
.RE
.PP
For
InnoDB
tables,
mysqldump
provides a way of making an online backup:
.sp
.RS 3n
.nf
shell> \fBmysqldump \-\-all\-databases \-\-single\-transaction > all_databases.sql\fR
.fi
.RE
.PP
This backup just needs to acquire a global read lock on all tables (using
FLUSH TABLES WITH READ LOCK) at the beginning of the dump. As soon as this lock has been acquired, the binary log coordinates are read and the lock is released. If and only if one long updating statement is running when the
FLUSH
statement is issued, the MySQL server may get stalled until that long statement finishes, and then the dump becomes lock\-free. If the update statements that the MySQL server receives are short (in terms of execution time), the initial lock period should not be noticeable, even with many updates.
.PP
For point\-in\-time recovery (also known as
\(lqroll\-forward,\(rq
when you need to restore an old backup and replay the changes that happened since that backup), it is often useful to rotate the binary log (see
Section\ 2.3, \(lqThe Binary Log\(rq) or at least know the binary log coordinates to which the dump corresponds:
.sp
.RS 3n
.nf
shell> \fBmysqldump \-\-all\-databases \-\-master\-data=2 > all_databases.sql\fR
.fi
.RE
.PP
Or:
.sp
.RS 3n
.nf
shell> \fBmysqldump \-\-all\-databases \-\-flush\-logs \-\-master\-data=2\fR
              \fB> all_databases.sql\fR
.fi
.RE
.PP
The
\fB\-\-master\-data\fR
and
\fB\-\-single\-transaction\fR
options can be used simultaneously, which provides a convenient way to make an online backup suitable for point\-in\-time recovery if tables are stored using the
InnoDB
storage engine.
.PP
For more information on making backups, see
Section\ 6.1, \(lqDatabase Backups\(rq, and
Section\ 6.2, \(lqExample Backup and Recovery Strategy\(rq.
.PP
If you encounter problems backing up views, please read the section that covers restrictions on views which describes a workaround for backing up views when this fails due to insufficient privileges. See
Section\ 4, \(lqRestrictions on Views\(rq.
.SH "COPYRIGHT"
.PP
Copyright 2007\-2008 MySQL AB
.PP
This documentation is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; version 2 of the License.
.PP
This documentation is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with the program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110\-1301 USA or see http://www.gnu.org/licenses/.
.SH "SEE ALSO"
For more information, please refer to the MySQL Reference Manual,
which may already be installed locally and which is also available
online at http://dev.mysql.com/doc/.
.SH AUTHOR
MySQL AB (http://www.mysql.com/).
