.\"     Title: \fBmysql_upgrade\fR
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 01/11/2008
.\"    Manual: MySQL Database System
.\"    Source: MySQL 5.0
.\"
.TH "\fBMYSQL_UPGRADE\fR" "1" "01/11/2008" "MySQL 5.0" "MySQL Database System"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
mysql_upgrade \- check tables for MySQL upgrade
.SH "SYNOPSIS"
.HP 24
\fBmysql_upgrade [\fR\fB\fIoptions\fR\fR\fB]\fR
.SH "DESCRIPTION"
.PP
\fBmysql_upgrade\fR
should be executed each time you upgrade MySQL. It checks all tables in all databases for incompatibilities with the current version of MySQL Server. If a table is found to have a possible incompatibility, it is checked. If any problems are found, the table is repaired.
\fBmysql_upgrade\fR
also upgrades the system tables so that you can take advantage of new privileges or capabilities that might have been added.
.PP
All checked and repaired tables are marked with the current MySQL version number. This ensures that next time you run
\fBmysql_upgrade\fR
with the same version of the server, it can tell whether there is any need to check or repair the table again.
.PP
\fBmysql_upgrade\fR
also saves the MySQL version number in a file named
\fImysql_upgrade_info\fR
in the data directory. This is used to quickly check if all tables have been checked for this release so that table\-checking can be skipped. To ignore this file, use the
\fB\-\-force\fR
option.
.PP
To check and repair tables and to upgrade the system tables,
\fBmysql_upgrade\fR
executes the following commands:
.sp
.RS 3n
.nf
mysqlcheck \-\-check\-upgrade \-\-all\-databases \-\-auto\-repair
mysql_fix_privilege_tables
.fi
.RE
.PP
\fBmysql_upgrade\fR
supersedes the older
\fBmysql_fix_privilege_tables\fR
script. In MySQL 5.0.19,
\fBmysql_upgrade \fR
was added as a shell script and worked only for Unix systems. As of MySQL 5.0.25,
\fBmysql_upgrade\fR
is an executable binary and is available on all systems. On systems older than those supporting
\fBmysql_upgrade\fR, you can execute the
\fBmysqlcheck\fR
command manually, and then upgrade your system tables as described in
\fBmysql_fix_privilege_tables\fR(1).
.PP
If you install MySQL from RPM packages on Linux, you must install the server and client RPMs.
\fBmysql_upgrade\fR
is included in the server RPM but requires the client RPM because the latter includes
\fBmysqlcheck\fR. (See
Section\ 4.9, \(lqInstalling MySQL from RPM Packages on Linux\(rq.)
.PP
For details about what is checked, see the description of the
FOR UPGRADE
option of the
CHECK TABLE
statement (see
Section\ 5.2.3, \(lqCHECK TABLE Syntax\(rq).
.PP
To use
\fBmysql_upgrade\fR, make sure that the server is running, and then invoke it like this:
.sp
.RS 3n
.nf
shell> \fBmysql_upgrade [\fR\fB\fIoptions\fR\fR\fB]\fR
.fi
.RE
.PP
After running
\fBmysql_upgrade\fR, stop the server and restart it so that it uses any changes that were made to the system tables.
.PP
\fBmysql_upgrade\fR
reads options from the command line and from the
[mysql_upgrade]
group in option files. It supports the following options:
.TP 3n
\(bu
\fB\-\-help\fR
.sp
Display a short help message and exit.
.TP 3n
\(bu
\fB\-\-basedir=\fR\fB\fIpath\fR\fR
.sp
The path to the MySQL installation directory.
.TP 3n
\(bu
\fB\-\-datadir=\fR\fB\fIpath\fR\fR
.sp
The path to the data directory.
.TP 3n
\(bu
\fB\-\-force\fR
.sp
Force execution of
\fBmysqlcheck\fR
even if
\fBmysql_upgrade\fR
has already been executed for the current version of MySQL. (In other words, this option causes the
\fImysql_upgrade_info\fR
file to be ignored.)
.TP 3n
\(bu
\fB\-\-user=\fR\fB\fIuser_name\fR\fR,
\fB\-u \fR\fB\fIuser_name\fR\fR
.sp
The MySQL username to use when connecting to the server. The default username is
root.
.TP 3n
\(bu
\fB\-\-verbose\fR
.sp
Verbose mode. Print more information about what the program does.
.sp
.RE
.PP
Other options are passed to
\fBmysqlcheck\fR
and to
\fBmysql_fix_privilege_tables\fR. For example, it might be necessary to specify the
\fB\-\-password[=\fR\fB\fIpassword\fR\fR\fB]\fR
option.
.SH "COPYRIGHT"
.PP
Copyright 2007\-2008 MySQL AB
.PP
This documentation is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; version 2 of the License.
.PP
This documentation is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with the program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110\-1301 USA or see http://www.gnu.org/licenses/.
.SH "SEE ALSO"
For more information, please refer to the MySQL Reference Manual,
which may already be installed locally and which is also available
online at http://dev.mysql.com/doc/.
.SH AUTHOR
MySQL AB (http://www.mysql.com/).
