.\"     Title: \fBndb_mgmd\fR
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 01/11/2008
.\"    Manual: MySQL Database System
.\"    Source: MySQL 5.0
.\"
.TH "\fBNDB_MGMD\fR" "1" "01/11/2008" "MySQL 5.0" "MySQL Database System"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ndb_mgmd \- the management server process
.SH "SYNOPSIS"
.HP 17
\fBndb_mgmd \fR\fB\fIoptions\fR\fR
.SH "DESCRIPTION"
.PP
The management server is the process that reads the cluster configuration file and distributes this information to all nodes in the cluster that request it. It also maintains a log of cluster activities. Management clients can connect to the management server and check the cluster's status.
.PP
It is not strictly necessary to specify a connectstring when starting the management server. However, if you are using more than one management server, a connectstring should be provided and each node in the cluster should specify its node ID explicitly.
.PP
See
Section\ 3.4.2, \(lqThe Cluster Connectstring\(rq, for information about using connectstrings.
Section\ 5.2, \(lqCommand Options for MySQL Cluster Processes\(rq, describes other options for
\fBndb_mgmd\fR.
.PP
The following files are created or used by
\fBndb_mgmd\fR
in its starting directory, and are placed in the
DataDir
as specified in the
\fIconfig.ini\fR
configuration file. In the list that follows,
\fInode_id\fR
is the unique node identifier.
.TP 3n
\(bu
\fIconfig.ini\fR
is the configuration file for the cluster as a whole. This file is created by the user and read by the management server.
Section\ 3, \(lqMySQL Cluster Configuration\(rq, discusses how to set up this file.
.TP 3n
\(bu
\fIndb_\fR\fI\fInode_id\fR\fR\fI_cluster.log\fR
is the cluster events log file. Examples of such events include checkpoint startup and completion, node startup events, node failures, and levels of memory usage. A complete listing of cluster events with descriptions may be found in
Section\ 6, \(lqManagement of MySQL Cluster\(rq.
.sp
When the size of the cluster log reaches one million bytes, the file is renamed to
\fIndb_\fR\fI\fInode_id\fR\fR\fI_cluster.log.\fR\fI\fIseq_id\fR\fR, where
\fIseq_id\fR
is the sequence number of the cluster log file. (For example: If files with the sequence numbers 1, 2, and 3 already exist, the next log file is named using the number
4.)
.TP 3n
\(bu
\fIndb_\fR\fI\fInode_id\fR\fR\fI_out.log\fR
is the file used for
stdout
and
stderr
when running the management server as a daemon.
.TP 3n
\(bu
\fIndb_\fR\fI\fInode_id\fR\fR\fI.pid\fR
is the process ID file used when running the management server as a daemon.
.SH "COPYRIGHT"
.PP
Copyright 2007\-2008 MySQL AB
.PP
This documentation is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; version 2 of the License.
.PP
This documentation is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with the program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110\-1301 USA or see http://www.gnu.org/licenses/.
.SH "SEE ALSO"
For more information, please refer to the MySQL Reference Manual,
which may already be installed locally and which is also available
online at http://dev.mysql.com/doc/.
.SH AUTHOR
MySQL AB (http://www.mysql.com/).
