.\"     Title: \fBndb_error_reporter\fR
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 01/11/2008
.\"    Manual: MySQL Database System
.\"    Source: MySQL 5.0
.\"
.TH "\fBNDB_ERROR_REPORTE" "1" "01/11/2008" "MySQL 5.0" "MySQL Database System"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ndb_error_reporter \- NDB error\-reporting utility
.SH "SYNOPSIS"
.HP 27
\fBndb_error_reporter \fR\fB\fIoptions\fR\fR
.SH "DESCRIPTION"
.PP
\fBndb_error_reporter\fR
creates an archive from data node and management node log files that can be used to help diagnose bugs or other problems with a cluster.
\fIIt is highly recommended that you make use of this utility when filing reports of bugs in MySQL Cluster\fR.
.PP
\fBUsage\fR:
.sp
.RS 3n
.nf
ndb_error_reporter \fIpath/to/config\-file\fR [\fIusername\fR] [\-\-fs]
.fi
.RE
.PP
This utility is intended for use on a management node host, and requires the path to the management host configuration file (\fIconfig.ini\fR). Optionally, you can supply the name of a user that is able to access the cluster's data nodes via SSH, in order to copy the data node log files. ndb_error_reporter then includes all of these files in archive that is created in the same directory in which it is run. The archive is named
\fIndb_error_report_\fR\fI\fIYYYYMMDDHHMMSS\fR\fR\fI.tar.bz2\fR, where
\fIYYYYMMDDHHMMSS\fR
is a datetime string.
.PP
If the
\fB\-\-fs\fR
is used, then the data node filesystems are also copied to the management host and included in the archive that is produced by this script. As data node filesystems can be extremely large even after being compressed, we ask that you please do
\fInot\fR
send archives created using this option to MySQL AB unless you are specifically requested to do so.
.SH "COPYRIGHT"
.PP
Copyright 2007\-2008 MySQL AB
.PP
This documentation is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; version 2 of the License.
.PP
This documentation is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with the program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110\-1301 USA or see http://www.gnu.org/licenses/.
.SH "SEE ALSO"
For more information, please refer to the MySQL Reference Manual,
which may already be installed locally and which is also available
online at http://dev.mysql.com/doc/.
.SH AUTHOR
MySQL AB (http://www.mysql.com/).
