.\"     Title: \fBndb_desc\fR
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 01/11/2008
.\"    Manual: MySQL Database System
.\"    Source: MySQL 5.0
.\"
.TH "\fBNDB_DESC\fR" "1" "01/11/2008" "MySQL 5.0" "MySQL Database System"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ndb_desc \- describe NDB tables
.SH "SYNOPSIS"
.HP 17
\fBndb_desc \fR\fB\fIoptions\fR\fR
.SH "DESCRIPTION"
.PP
\fBndb_desc\fR
provides a detailed description of one or more
NDB
tables.
.PP
\fBUsage\fR:
.sp
.RS 3n
.nf
ndb_desc \-c \fIconnect_string\fR \fItbl_name\fR \-d \fIdb_name\fR
.fi
.RE
.PP
\fBSample Output\fR:
.PP
MySQL table creation and population statements:
.sp
.RS 3n
.nf
USE test;
CREATE TABLE fish (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(20),
    PRIMARY KEY pk (id),
    UNIQUE KEY uk (name)
) ENGINE=NDBCLUSTER;
INSERT INTO fish VALUES 
    ('','guppy'), ('','tuna'), ('','shark'), 
    ('','manta ray'), ('','grouper'), ('','puffer');
.fi
.RE
.PP
Output from
\fBndb_desc\fR:
.sp
.RS 3n
.nf
shell> \fB./ndb_desc \-c localhost fish \-d test \-p\fR
\-\- fish \-\-
Version: 16777221
Fragment type: 5
K Value: 6
Min load factor: 78
Max load factor: 80
Temporary table: no
Number of attributes: 2
Number of primary keys: 1
Length of frm data: 268
Row Checksum: 1
Row GCI: 1
TableStatus: Retrieved
\-\- Attributes \-\-
id Int PRIMARY KEY DISTRIBUTION KEY AT=FIXED ST=MEMORY
name Varchar(20;latin1_swedish_ci) NULL AT=SHORT_VAR ST=MEMORY
\-\- Indexes \-\-
PRIMARY KEY(id) \- UniqueHashIndex
uk(name) \- OrderedIndex
PRIMARY(id) \- OrderedIndex
uk$unique(name) \- UniqueHashIndex
\-\- Per partition info \-\-
Partition  Row count  Commit count  Frag fixed memory  Frag varsized memory
2          2          2             65536              327680
1          2          2             65536              327680
3          2          2             65536              327680
NDBT_ProgramExit: 0 \- OK
.fi
.RE
.PP
\fBAdditional Options\fR:
.TP 3n
\(bu
\fB\-\-extra\-partition\-info\fR,
\fB\-p\fR
.sp
Prints additional information about the table's partitions.
.TP 3n
\(bu
Information about multiple tables can be obtained in a single invocation of
\fBndb_desc\fR
by using their names, separated by spaces. All of the tables must be in the same database.
.SH "COPYRIGHT"
.PP
Copyright 2007\-2008 MySQL AB
.PP
This documentation is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; version 2 of the License.
.PP
This documentation is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with the program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110\-1301 USA or see http://www.gnu.org/licenses/.
.SH "SEE ALSO"
For more information, please refer to the MySQL Reference Manual,
which may already be installed locally and which is also available
online at http://dev.mysql.com/doc/.
.SH AUTHOR
MySQL AB (http://www.mysql.com/).
