ALTER TABLE MALNUTRITIONCONTROL DROP FOREIGN KEY FK_MALNUTRITIONCONTROL_ADMISSION;
ALTER TABLE MALNUTRITIONCONTROL ADD COLUMN MLN_PAT_ID INT(11) NULL DEFAULT NULL AFTER MLN_ADM_ID, CHANGE COLUMN MLN_ADM_ID MLN_ADM_ID INT(11) NULL DEFAULT NULL;
ALTER TABLE MEDICALDSRSTOCKMOVWARD ADD COLUMN MMVN_PAT_AGE SMALLINT NOT NULL AFTER MMVN_PAT_ID;
ALTER TABLE MEDICALDSRSTOCKMOVWARD ADD COLUMN MMVN_PAT_WEIGHT FLOAT NOT NULL AFTER MMVN_PAT_AGE;
UPDATE MEDICALDSRSTOCKMOVWARD SET MMVN_PAT_AGE = (SELECT PAT_AGE from PATIENT WHERE PATIENT.PAT_ID = MEDICALDSRSTOCKMOVWARD.MMVN_PAT_ID) WHERE EXISTS (SELECT 1 from PATIENT WHERE PATIENT.PAT_ID = MEDICALDSRSTOCKMOVWARD.MMVN_PAT_ID);

DROP TABLE IF EXISTS MEDICALDSRWARD;
CREATE TABLE MEDICALDSRWARD (
  MDSRWRD_WRD_ID_A char(1) NOT NULL,
  MDSRWRD_MDSR_ID int(11) NOT NULL,
  MDSRWRD_IN_QTI float,
  MDSRWRD_OUT_QTI float,
  PRIMARY KEY (MDSRWRD_WRD_ID_A, MDSRWRD_MDSR_ID)
);

INSERT INTO MEDICALDSRWARD(MDSRWRD_WRD_ID_A, MDSRWRD_MDSR_ID, MDSRWRD_IN_QTI, MDSRWRD_OUT_QTI)
SELECT MMV_WRD_ID_A AS WARD, MMV_MDSR_ID AS MED, SUM(MMV_QTY), 0 AS TOTAL FROM MEDICALDSRSTOCKMOV WHERE MMV_MMVT_ID_A like "discharge" AND MMV_WRD_ID_A is not null GROUP BY MMV_WRD_ID_A, MMV_MDSR_ID;
  
INSERT INTO MEDICALDSRWARD(MDSRWRD_WRD_ID_A, MDSRWRD_MDSR_ID, MDSRWRD_OUT_QTI)
SELECT OUT_QTI.WARD, OUT_QTI.MED, OUT_QTI.QTI FROM
(SELECT MMVN_WRD_ID_A AS WARD, MMVN_MDSR_ID AS MED, SUM(MMVN_MDSR_QTY) AS QTI FROM MEDICALDSRSTOCKMOVWARD GROUP BY MMVN_WRD_ID_A, MMVN_MDSR_ID) AS OUT_QTI
ON DUPLICATE KEY UPDATE MDSRWRD_OUT_QTI = QTI;
