CREATE TABLE SMS (
  SMS_ID INT(11) NOT NULL AUTO_INCREMENT ,
  SMS_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  SMS_DATE_SCHED DATETIME NOT NULL ,
  SMS_NUMBER VARCHAR(45) NOT NULL ,
  SMS_TEXT VARCHAR(160) NOT NULL ,
  SMS_DATE_SENT DATETIME NULL ,
  SMS_USER VARCHAR(50) NOT NULL DEFAULT 'admin' ,
  PRIMARY KEY (SMS_ID) 
);

INSERT INTO MENUITEM VALUES ('smsmanager', 'angal.menu.btn.smsmanager', 'angal.menu.smsmanager', 'x', 'M', 'generaldata', 'org.isf.sms.gui.SmsBrowser','N', 9);
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','smsmanager','Y');
