ALTER TABLE USER CHANGE COLUMN US_PASSWD US_PASSWD VARCHAR(60) NOT NULL DEFAULT '' ;
UPDATE USER SET US_PASSWD = "$2a$10$FI/PMO0oSHHosF2PX8l3QuB0DJepVfnynbLZ9Zm2711bF2ch8db2S" WHERE US_ID_A LIKE "admin";
UPDATE USER SET US_PASSWD = "$2a$10$b0WlANdaNV7Ukn/klFGt3.euZ7PaHuJI6TtBSM2vdxkavvkUDbpo2" WHERE US_ID_A LIKE "guest";
