ALTER TABLE PATIENT MODIFY COLUMN PAT_AGE INT NOT NULL DEFAULT 0;
ALTER TABLE OPD MODIFY COLUMN OPD_AGE INT NOT NULL DEFAULT 0;
DELETE FROM GROUPMENU WHERE GM_MNI_ID_A = 'laboratoryresulttype';
DELETE FROM MENUITEM WHERE MNI_ID_A = 'laboratoryresulttype';
UPDATE MENUITEM SET MNI_CLASS = 'org.isf.lab.gui.LabBrowser', MNI_IS_SUBMENU = 'N' WHERE MNI_ID_A = 'laboratory';
DELETE FROM GROUPMENU WHERE GM_MNI_ID_A = 'labbrowsing';
DELETE FROM MENUITEM WHERE MNI_ID_A = 'labbrowsing';