INSERT INTO MENUITEM VALUES ('data','angal.admission.data','angal.admission.data','x','D','admission','none','N',3);
INSERT INTO MENUITEM VALUES ('btnadmnew','angal.admission.newpatient','angal.admission.newpatient','x','N','admission','none','N',0);
INSERT INTO MENUITEM VALUES ('btnadmedit','angal.admission.editpatient','angal.admission.editpatient','x','E','admission','none','N',1);
INSERT INTO MENUITEM VALUES ('btnadmopd','angal.admission.opd','angal.admission.admission','x','O','admission','none','N',5);
INSERT INTO MENUITEM VALUES ('btnadmadm','angal.admission.admission','angal.admission.admission','x','A','admission','none','N',4);
INSERT INTO MENUITEM VALUES ('btnadmdel','angal.admission.deletepatient','angal.admission.deletepatient','x','L','admission','none','N',2);
INSERT INTO MENUITEM VALUES ('btnadmmer','angal.admission.merge','angal.admission.merge','x','L','admission','none','N',2);
INSERT INTO MENUITEM VALUES ('btndataeditpat','angal.admission.editpatient','angal.admission.editpatient','x','P','data','none','N',0);
INSERT INTO MENUITEM VALUES ('btndatamalnut','angal.admission.malnutritioncontrol','angal.admission.malnutritioncontrol','x','M','data','none','N',3);
INSERT INTO MENUITEM VALUES ('btndatadel','angal.admission.deletem','angal.admission.deletem','x','D','data','none','N',2);
INSERT INTO MENUITEM VALUES ('btndataedit','angal.admission.editm','angal.admission.editm','x','E','data','none','N',1);
INSERT INTO MENUITEM VALUES ('btnopddel','angal.opd.delete','angal.opd.delete','x','D','opd','none','N',2);
INSERT INTO MENUITEM VALUES ('btnopdedit','angal.opd.edit','angal.opd.edit','x','E','opd','none','N',1);
INSERT INTO MENUITEM VALUES ('btnopdnew','angal.opd.new','angal.opd.new','x','N','opd','none','N',0);
INSERT INTO MENUITEM VALUES ('btnpharmaceuticaldel','angal.medicals.delete','angal.medicals.delete','x','D','medicals','none','N',2);
INSERT INTO MENUITEM VALUES ('btnpharmaceuticaledit','angal.medicals.edit','angal.medicals.edit','x','E','medicals','none','N',1);
INSERT INTO MENUITEM VALUES ('btnpharmaceuticalnew','angal.medicals.new','angal.medicals.new','x','N','medicals','none','N',0);
INSERT INTO MENUITEM VALUES ('btnlaboratorydel','angal.lab.delete','angal.lab.delete','x','D','laboratory','none','N',2);
INSERT INTO MENUITEM VALUES ('btnlaboratoryedit','angal.lab.edit','angal.lab.edit','x','E','laboratory','none','N',1);
INSERT INTO MENUITEM VALUES ('btnlaboratorynew','angal.lab.new','angal.lab.new','x','N','laboratory','none','N',0);

INSERT INTO USERGROUP VALUES("guest","Read Only Users");
INSERT INTO USER VALUES("guest","guest","guest","guest");

INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','data','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','btnadmdel','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','btnadmadm','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','btnadmedit','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','btnadmnew','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','btnadmopd','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','btnadmmer','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','btnlaboratorydel','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','btnlaboratoryedit','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','btnlaboratorynew','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','btnopdedit','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','btnopddel','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','btnopdnew','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','btndatamalnut','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','btndatadel','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','btndataedit','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','btndataeditpat','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','btnpharmaceuticaldel','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','btnpharmaceuticaledit','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','btnpharmaceuticalnew','Y');

INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','admtype','N');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','disctype','N');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','admission','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','disease','N');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','exams','N');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','exit','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','file','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','generaldata','N');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','groups','N');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','help','N');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','hospital','N');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','laboratory','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','medicals','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','medicalstock','N');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','operation','N');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','pharmacy','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','statistics','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','opd','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','users','N');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','usersusers','N');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','vaccine','N');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','ward','N');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','types','N');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','pretreatmenttype','N');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','diseasetype','N');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','medstockmovtype','N');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','examtype','N');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','operationtype','N');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','deliverytype','N');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','medicalstype','N');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','delresulttype','N');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','printing','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','examlist1','Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('guest','diseaselist','Y');
