ALTER TABLE MEDICALDSRSTOCKMOVWARD ADD COLUMN MMVN_WRD_ID_A_FROM varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL;
ALTER TABLE MEDICALDSRSTOCKMOVWARD ADD COLUMN MMVN_WRD_ID_A_TO varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL;
