SELECT ADM_ID, ADM_PAT_ID,
(SELECT WRD_NAME FROM ward WHERE WRD_ID_A = ADM_WRD_ID_A) AS WARD,
(SELECT PAT_NAME FROM patient WHERE PAT_ID = ADM_PAT_ID) AS PATIENT,
(SELECT PAT_AGE FROM patient WHERE PAT_ID = ADM_PAT_ID) AS AGE,
(SELECT PAT_SEX FROM patient WHERE PAT_ID = ADM_PAT_ID) AS SEX,
DATE(ADM_DATE_ADM) ADMISSION_DATE,
(SELECT ADMT_DESC FROM admissiontype WHERE ADMT_ID_A = ADM_ADMT_ID_A_ADM) AS ADM_TYPE,
(SELECT DIS_DESC FROM disease WHERE DIS_ID_A = ADM_IN_DIS_ID_A) AS DISEASE_IN, 
DATE(ADM_DATE_DIS) DISCHARGE_DATE,
(SELECT DIST_DESC FROM dischargetype WHERE DIST_ID_A = ADM_DIST_ID_A) AS DIS_TYPE,
(SELECT DIS_DESC FROM disease WHERE DIS_ID_A = ADM_OUT_DIS_ID_A) AS DISEASE_OUT_1, 
(SELECT DIS_DESC FROM disease WHERE DIS_ID_A = ADM_OUT_DIS_ID_A_2) AS DISEASE_OUT_2, 
(SELECT DIS_DESC FROM disease WHERE DIS_ID_A = ADM_OUT_DIS_ID_A_3) AS DISEASE_OUT_3,
IF (DATEDIFF(ADM_DATE_DIS, ADM_DATE_ADM) = 0, 1, DATEDIFF(ADM_DATE_DIS, ADM_DATE_ADM)) AS DAYS
FROM admission
WHERE ADM_DELETED = 'N'
AND ADM_DATE_DIS IS NOT NULL