ALTER TABLE MEDICALDSR ADD COLUMN MDSR_CODE varchar(5) NOT NULL AFTER MDSR_MDSRT_ID_A;
ALTER TABLE MEDICALDSR ADD COLUMN MDSR_PCS_X_PCK integer NOT NULL AFTER MDSR_INI_STOCK_QTI;

ALTER TABLE PATIENT ADD COLUMN PAT_MOTH_NAME varchar(50) NOT NULL DEFAULT '' AFTER PAT_TELE;
ALTER TABLE PATIENT ADD COLUMN PAT_FATH_NAME varchar(50) NOT NULL DEFAULT '' AFTER PAT_MOTH;
ALTER TABLE PATIENT ADD COLUMN PAT_BTYPE varchar(7) NOT NULL DEFAULT 'Unknown';
ALTER TABLE PATIENT ADD COLUMN PAT_BDATE varchar(50) NOT NULL DEFAULT '' AFTER PAT_NAME;
ALTER TABLE PATIENT MODIFY COLUMN PAT_AGE varchar(50) NOT NULL;

ALTER TABLE OPD ADD COLUMN OPD_PAT_FULLNAME varchar(50) NOT NULL DEFAULT '' AFTER OPD_PAT_ID;
ALTER TABLE OPD MODIFY COLUMN OPD_AGE varchar(50) NOT NULL;
ALTER TABLE OPD ADD COLUMN OPD_NOTE TEXT NOT NULL AFTER OPD_REFERRAL_TO;

UPDATE MENUITEM SET MNI_CLASS='org.isf.menu.gui.UserGroupBrowsing' WHERE MNI_ID_A='groups';