DELIMITER //

DROP PROCEDURE IF EXISTS calcAmount;
CREATE PROCEDURE calcAmount()
BEGIN
    DECLARE v_id INT;
	DECLARE v_amount DOUBLE;
    DECLARE done INT DEFAULT FALSE;
    DECLARE cur CURSOR FOR SELECT BLL_ID, AMOUNT FROM 
							(SELECT BLL_ID, BLL_AMOUNT, SUM(BLI_ITEM_AMOUNT * BLI_QTY) AS AMOUNT
							FROM BILLS JOIN BILLITEMS ON BLL_ID = BLI_ID_BILL
							WHERE BLI_ITEM_AMOUNT > 0
							GROUP BY BLL_ID
							ORDER BY BLL_ID) BILLS
							WHERE BLL_AMOUNT <> AMOUNT;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;

    OPEN cur;
    read_loop: LOOP
        FETCH cur INTO v_id, v_amount;
        IF done THEN
            LEAVE read_loop;
        END IF;
        UPDATE BILLS SET BLL_AMOUNT = v_amount WHERE BLL_ID = v_id;
    END LOOP;
  CLOSE cur;

END; //
DELIMITER ;

CALL calcAmount();