ALTER TABLE WARD ADD COLUMN WRD_IS_MALE TINYINT(1) NOT NULL DEFAULT '1' AFTER WRD_IS_PHARMACY, 
	ADD COLUMN WRD_IS_FEMALE TINYINT(1) NOT NULL DEFAULT '1' AFTER WRD_IS_MALE;
UPDATE WARD SET WRD_IS_MALE = 0 WHERE WRD_ID_A = 'M';
