DROP TABLE IF EXISTS THERAPIES;
CREATE TABLE  THERAPIES (
  THR_ID int(11) NOT NULL AUTO_INCREMENT,
  THR_CODE int(11) NOT NULL,
  THR_PAT_ID int(11) NOT NULL,
  THR_STARTDATE datetime NOT NULL,
  THR_ENDDATE datetime NOT NULL,
  THR_MDSR_ID int(11) NOT NULL,
  THR_QTY double NOT NULL,
  THR_UNT_ID int(11) NOT NULL,
  THR_FREQINDAY int(11) NOT NULL,
  THR_FREQINPRD int(11) NOT NULL,
  THR_NOTE text,
  THR_NOTIFY tinyint(1) NOT NULL DEFAULT '0',
  THR_SMS tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (THR_ID)
) ENGINE=MyISAM;

DROP TABLE IF EXISTS VISITS;
CREATE TABLE VISITS (
  VST_ID int(11) NOT NULL AUTO_INCREMENT,
  VST_PAT_ID int(11) NOT NULL,
  VST_DATE datetime NOT NULL,
  VST_NOTE text,
  PRIMARY KEY (VST_ID)
) ENGINE=MyISAM;

INSERT INTO MENUITEM VALUES ('btnadmtherapy','angal.admission.therapy','angal.admission.therapy','x','T','admission','none','N',6);

INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A,  GM_ACTIVE) VALUES ('admin','btnadmtherapy','Y');

